# Generated by Django 4.1.4 on 2022-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('display_resolution', models.CharField(max_length=50, verbose_name='Display Resolution')),
                ('display_size', models.CharField(max_length=50, verbose_name='Display Size')),
                ('display_type', models.CharField(max_length=50, verbose_name='Display Type')),
                ('processor_model', models.CharField(max_length=50, verbose_name='Processor model')),
            ],
        ),
    ]
