# Generated by Django 4.1.4 on 2022-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='release_date',
            field=models.DateTimeField(null=True, verbose_name='Release Date'),
        ),
    ]
