# Generated by Django 4.1.4 on 2022-12-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_smartphone_add_date_smartphone_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
