# Generated by Django 4.1.4 on 2022-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_smartphone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Release Date'),
        ),
    ]
