# Generated by Django 4.1.4 on 2023-04-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_images_reviewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='products/reviews_image'),
        ),
    ]
