# Generated by Django 4.1.4 on 2023-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_order_phone_alter_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='item_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
