# Generated by Django 4.1.4 on 2023-05-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_order_address_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
